### ISSUE TITLE
TTC?

### ISSUE THREAD

**Issue by aaronbell** [Font-Kai/Kaisei-Opti#5]
Given that the four Kaisei fonts share a significant portion of their glyph sets (Kanji / Latin / symbols), does it make sense to build them as a single TTC file? 

At the least, I think it makes sense to merge them into a single repository where the shared glyphs are in one source, the unique glyphs in separate repositories, and the fonts assembled at build time.

**Comment by aaronbell** [comment]
Thoughts @davelab6 / @m4rc1e ?

**Comment by m4rc1e** [comment]
I don't think our api can serve TTC fonts so please keep them as ttf.

**Comment by aaronbell** [comment]
Will do. I think I'll do the source division as mentioned above, though, since that'll simplify future maintenance.
