### ISSUE TITLE
Shared Kanji file too large for normal github

### ISSUE THREAD

**Issue by aaronbell** [Font-Kai/Kaisei-Opti#7]
The FontKai fonts are essentially four unique sets of kana that are added to a central set of shared Latin / Kanji characters. So in order to avoid a situation in the future where we need to make the same change to four different files and instead aim to preserve the idea of “single master” for each glyph, I have split the source files apart into what is unique to a given font, and what is shared:
 
FK-Kaisei-Decol
FK-Kaisei-HarunoUmi
FK-Kaisei-Opti
FK-Kaisei-Tokumin
FK-Kaisei-Shared
 
And I put together a build script that assembles them (basically loads each of the four, and then merges in the appropriate shared glyphs).
 
The issue is that FK-Kaisei-Shared is now 140MB (it contains 4 weights of full Adobe-Japan1-3 Kanji), which is over the Github limit of 100MB. So we will need to use Git Large File Storage (https://git-lfs.github.com) in order to version it.

**Comment by davelab6** [comment]
Is there any reason not to use ufo for this? :)

**Comment by aaronbell** [comment]
For this work, I've tended to prefer to keep the source format in the format of choice for the designer. If Mr. Kanai is OK with switching the source over to UFO, I'd be happy to do so. :)

**Comment by aaronbell** [comment]
I discovered that a zipped version is OK, and will include a UFO version as well. That way it is easier for him to work on the Glyphs source and we can rebuild the UFO as necessary (the build script includes an args for that).
